### ISSUE TITLE
cmake: add version number in csg/tools check

### ISSUE THREAD

**Issue by GoogleCodeExporter** [votca/csg#103]
```
csg builds only with exactly the same of tools, e.g.
1.2.0 with 1.2.0 and 1.3-dev with 1.3-dev.

We need to a an extra check for that to FindVOTCA_Tools.cmake
```

Original issue reported on code.google.com by `christop...@gmail.com` on 20 Jun 2011 at 8:41

**Comment by junghans** [comment]
Super project has been start: votca/buildutil@f42ec0a66c04ee4a97cec7dc3546903d18bbb48d, see the [global](https://github.com/votca/buildutil/tree/global) branch for further development!

**Comment by junghans** [comment]
cmake-3.0 has library interface, which might make that very easy.
https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#interface-libraries

**Comment by junghans** [comment]
We switched to imported targets everywhere, so now CMake should provide the ability to check version, too.
