### ISSUE TITLE
csg_boltzmann: --excl option is broken/not implemented anymore

### ISSUE THREAD

**Issue by junghans** [votca/csg#177]
In 6991f1e4a308f23f546181fed57a70d8ba286745 the `--excl` option of `csg_boltzmann` got broken. @ruehle drafted up some come [here](https://github.com/votca/csg/commit/6991f1e4a308f23f546181fed57a70d8ba286745#diff-96f1ebad49076ca88c838cbdef42b6beR100), but it still needs some work!

@votca/csg: Should we fix it or drop the `--excl` option?

@MrTheodor: Have you used that option before?

**Comment by SudharsanP** [comment]
I used it to check whether all the excluding interactions for molecules were listed or not (when I use mixtures). But other than that I don't use it for anything really.
