### ISSUE TITLE
xmltopologyparser: improper parsing of bead lists in <bonded> terms

### ISSUE THREAD

**Issue by jkrajniak** [votca/csg#195]
The bead list in `<beads>` formated by using `\t` is not correctly parsed.

see: https://groups.google.com/forum/#!topic/votca/WAP-7Vzg8_Y

**Comment by junghans** [comment]
VOTCA Tools  has a tokenizer, which should work on tabs, spaces and both kinds of endlines.

**Comment by junghans** [comment]
Bug fix should go into the `stable` branch for v1.4.
