### ISSUE TITLE
CMake Error at CMakeLists.txt:136 (message):   Could not find needed header - fstream

### ISSUE THREAD

**Issue by NickyaZhong** [votca/csg#200]
> sh build.sh -p $prefix -ud tools

`get_webversion: Could not fetch new version number
get_webversion: Could not fetch new version number
This is VOTCA build.sh, version 2.1.1
Install prefix is '/home/internship2/Software/VOTCA/votca-1.4'
Using 9 jobs for make/ninja
Working on tools
Source dir (tools) is already there - skipping checkout
updating git repository tools from origin/master
We are on branch master
Already up-to-date.
cmake -DCMAKE_INSTALL_PREFIX='/home/internship2/Software/VOTCA/votca-1.4'  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON .
-- Found Git: /usr/bin/git (found version "1.7.11.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.21") 
-- Checking for module 'gsl'
--   No package 'gsl' found
-- Found GSL: /home/internship2/Software/gsl/lib/libgsl.so  
-- Looking for gsl_linalg_QR_decomp in /home/internship2/Software/gsl/lib/libgsl.so;
-- Looking for gsl_linalg_QR_decomp in /home/internship2/Software/gsl/lib/libgsl.so; - not found
-- Found GSLCBLAS: /home/internship2/Software/gsl/lib/libgslcblas.so  
-- Looking for cblas_dsyrk in /home/internship2/Software/gsl/lib/libgslcblas.so;
-- Looking for cblas_dsyrk in /home/internship2/Software/gsl/lib/libgslcblas.so; - found
-- Looking for gsl_linalg_QR_lssolve in /home/internship2/Software/gsl/lib/libgsl.so;/home/internship2/Software/gsl/lib/libgslcblas.so;
-- Looking for gsl_linalg_QR_lssolve in /home/internship2/Software/gsl/lib/libgsl.so;/home/internship2/Software/gsl/lib/libgslcblas.so; - found
-- Intel(R) MKL could not be found.
-- GSL found, overloading uBLAS prod()
-- Checking for module 'fftw3'
--   No package 'fftw3' found
-- Found FFTW3: /home/xiaopeng/software/fftw-3.3.4d/lib/libfftw3.so  
-- Looking for fftw_plan_r2r_1d in /home/xiaopeng/software/fftw-3.3.4d/lib/libfftw3.so;
-- Looking for fftw_plan_r2r_1d in /home/xiaopeng/software/fftw-3.3.4d/lib/libfftw3.so; - found
-- Looking for assert.h
-- Looking for assert.h - found
-- Looking for math.h
-- Looking for math.h - found
-- Looking for stdio.h
-- Looking for stdio.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for C++ include cmath
-- Looking for C++ include cmath - found
-- Looking for C++ include fstream
-- Looking for C++ include fstream - not found
CMake Error at CMakeLists.txt:136 (message):
  Could not find needed header - fstream

-- Configuring incomplete, errors occurred!
See also "/home/internship2/Software/VOTCA/src/csg-1.4/tools/CMakeFiles/CMakeOutput.log".
See also "/home/internship2/Software/VOTCA/src/csg-1.4/tools/CMakeFiles/CMakeError.log".`

**Comment by junghans** [comment]
What compiler are you using? Can you attach your `CMakeError.log`?

**Comment by junghans** [comment]
You can also use the mailing list: https://groups.google.com/forum/#!forum/votca

**Comment by junghans** [comment]
No response - closing!
