### ISSUE TITLE
-tableb option in run_gromacs.sh

### ISSUE THREAD

**Issue by schererc** [votca/csg#210]
At the moment I am cleaning up the csg tutorials. I figured out that at least with my installed Gromacs version (5.1) the option -tableb table_a1.xvg table_b1.xvg causes an error in the simulation step if I run any ibi calculation with tabulated bonded interactions (wether they are updated or not). If I run without the -tableb option it works (tables have to have the same number as in the topol.top file). If I simply remove the option, it works (at least for Gromacs 5.1)

**Comment by junghans** [comment]
I am guessing hit by:
<https://groups.google.com/forum/#!msg/votca/fGgjXpJQqmI/npxPH-2aPQAJ>

With Gromacs-2016 released on [Aug 5th 2016](https://mailman-1.sys.kth.se/pipermail/gromacs.org_gmx-users/2016-August/107718.html), please leave gromacs-5 alone as it is unsupported by upstream now.

**Comment by schererc** [comment]
Ok, I should have probably known this.

So I will leave the script as it is and try with a more recent Gromacs version.

**Comment by junghans** [comment]
Did it fix it?

**Comment by junghans** [comment]
fixed?

**Comment by schererc** [comment]
Yes, with the newest Gromacs version it worked with the -tableb option

Am 21.07.2017 16:40 schrieb "Christoph Junghans" <notifications@github.com>:
