### ISSUE TITLE
PDB Reader Update

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#229]
Apparently pdb reader does not have the ability to read the connectivity information from .pdb files. This needs to be added.

**Comment by JoshuaSBrown** [comment]
It appears that the official .pdb file format only reserve field sizes of 5 character. E.g. it might not be ideal to use the .pdb file format if you have more than 99999 atoms as the field widths are only allowed to be so large and so the CONECT key word is limited to atoms of of ids of 99999  and less.

**Comment by junghans** [comment]
That is true.

**Comment by JoshuaSBrown** [comment]
I would like to keep this in the support for the pdbreader, as this is a widely supported file format. It will increase portability for users, as opposed to the topology reader, which as far as I know is specific to VOTCA. Unless, we would want to develop a tool to convert several .pdb files to a single .xml file which could then be provided as an input for VOTCA?

**Comment by JoshuaSBrown** [comment]
So it looks like VMD doesn't strictly follow the .pdb file format. 

`Features

Can VMD load PDB files containing more than 99,999 atoms?

Yes. VMD can load a properly formatted PDB file with an arbitrary number of atoms. VMD is able to do this because it ignores the atom indices stored the PDB file itself and instead it uses its own internal numbering scheme. As long as your PDB file follows the strict column rules from the PDB spec, VMD doesn't care how many atoms are in the file.`

http://www.ks.uiuc.edu/Research/vmd/allversions/vmd_faq.html

Perhaps we should ignore the max number of atoms limitation as well.

**Comment by JoshuaSBrown** [comment]
They load trajectories from .pdb files by using the following naming conventions. Apparently they do not have more than one frame per file. 
http://www.ks.uiuc.edu/Research/vmd/script_library/scripts/animatepdbs/

**Comment by junghans** [comment]
VOTCA ignores the ids as well! So that we can read more than 99999 atoms!

I guess, that is ok if atoms are in ascending order.

**Comment by JoshuaSBrown** [comment]
I'm going to suggest we take a similar approach. 
-tra file0.pdb
Will indicate the trajectories are started at file0.pdb and by default will parse through any other files with numbers larger than the value infront of 0. 
file1.pdb, file2.pdb etc...
If you were to start at a larger value file12.pdb it would automatically search for file13.pdb and so on.

**Comment by junghans** [comment]
The pdb format allow multi-frame files!

**Comment by JoshuaSBrown** [comment]
Ah, I have another solution. The original .pdb format has an upgrade with the extension .pdbx. We can therefore design plugins for both scenarios. It seems that the .pdbx format is not limited to 99,999 atoms.

**Comment by JoshuaSBrown** [comment]
Ok, I see the ENDMDL keyword is what is used to denote the end of a frame and the start of another. Not exactly obvious from the documentation.

**Comment by JoshuaSBrown** [comment]
It might be the case that when you were originally reading .pdb files you did not need to worry about how many atoms are in the file but it becomes a problem when you read topological data using the CONECT keyword. As there are 5 columns allowed to specify the id of each bonded atom. 
There are 4 ways we can proceed from here:
1. Ignore the column specifications (less rigid .pdb file format) / This kind of seems to be the approach you have taken so far. As you are placing more than 99,999 atoms in a given .pdb file. It was not an issue before I think because you were not looking reading topological information. 
2. Break large systems into more than one file using the SPLIT keyword
3. Recommend a different but similar file format for systems greater than 99,999 atoms such as .pdbx. 
4. Keep the .pdb reader as is and calculate bond pairs internally. 
I Would prefer option 3, or option 1.

**Comment by junghans** [comment]
I would go with 1. and throw a runtime error suggesting to use the xml topology reader if the pdb has more than 99999 atoms and `CONECT` in them.

On the plus side, one can always use a xml topology together with an pdb trajectory.

**Comment by JoshuaSBrown** [comment]
Since .pdb files only reserve two characters for specifying the charge of an atom, it is impossible to pass partial charges through the .pdb file. It appears most people just leave this column blank. So we will default to passing a value of 0 for the partial charge.
