### ISSUE TITLE
Consolidate dlpoly readers into single file

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#231]
For the sake of consistency in the design of file input readers. It makes some sense to confine the readers to a single file. Though this is not exactly a high priority.

**Comment by junghans** [comment]
I am not sure how much sense that makes. The `.dlph` and `.dlpc` trajectory format has much less information in it as the `.dlpf` topology format. So there isn't much we would gain in terms of reducing code duplication.

But that is a question for @abrukhno.

**Comment by JoshuaSBrown** [comment]
Is the thumbs down, because I didn't provide an explanation?

**Comment by junghans** [comment]
Let’s see what @abrukhno thinks, he wrote most of the code!

**Comment by abrukhno** [comment]
Hi, sorry for a bit of delay (it's Saturday after all).
I am not sure I follow the idea. In the case of DL_POLY configuration (.dlpc) and trajectory (.dlph) formats are only slightly different (but I think reading either is combine already in one piece of code) whereas topology format is **completely** different, as it's not about configuration rather molecular structure and force-field. So what is the suggestion?

**Comment by JoshuaSBrown** [comment]
Well my thoughts were as follows: combining the two readers in same file is more consistent with how the file readers are formatted. From the stand point of maintainability, if all the readers follow the same pattern it is easier to understand what is going on. I think the point @junghans is making is that because the readers are configured so differently (for the DL_POLY trj and top files) it will not result in a reduction in the amount of code (so it's kind of a waste of time).

**Comment by abrukhno** [comment]
Hi Joshua, could you please provide more detail as to how you suggest to combine the two readers? -by simply having them as separate routines in the same file, or in the same routine/function? Either way I do not see much of a benefit, only extra work and debugging. Sorry if I misunderstood you.

**Comment by JoshuaSBrown** [comment]
You are right there is not much benefit. My arguments are mostly trivial, and this is a low priority issue if at all. What I'm trying to illustrate by bringing this up is that the more similar your methods are the easier it is to follow logic of the code between the different methods. 

Most of the topology and trajectory readers are in the same file but this one and a few others are not. Which is not a big deal, but if the code base continues to grow small inconsistencies can add up and complicate the code base unnecessarily. For this particular reader, there would not really be much to change. 

Most of the readers follow this format in the header file:

```class SomeReader :
    public TrajectoryReader, public TopologyReader
{
    public:
        SomeReader() {}
        ~SomeReader() {}

        /// open a topology file
        bool ReadTopology(string file, Topology &top);

        /// open a trejectory file
        bool Open(const string &file);
        /// read in the first frame
        bool FirstFrame(Topology &top);
        /// read in the next frame
        bool NextFrame(Topology &top);

        void Close();
        // reader specific methods
    private:
        ifstream _fl;
        bool _topology;
        //reader specific variables
};
```

Where as the dlpoly has two header files

```class DLPOLYTrajectoryWriter
   : public TrajectoryWriter
{
 public:
  // open transformed trajectory file
  void Open(string file, bool bAppend=false);
  // close transformed trajectory file
  void Close();
  // write a frame into transformed trajectory file
  void Write(Topology *conf);

  /// set/get the created configuration or trajectory file name: 
  /// <name>.dlpc or <name>.dlph (convention: ".dlpc"="CONFIG_CGV", ".dlph"="HISTORY_CGV")
  void   setFname(string name) { _fname = name; return; }
  string getFname()            { return _fname; }

  /// set/check the flag for the created file as configuration, i.e. not trajectory format
  void setIsConfig(bool isConf) { _isConfig=isConf;  return; }
  bool getIsConfig()            { return _isConfig; }

 private:
  ofstream _fl;
  string _fname;
  bool _isConfig;
};
```
And 
```class DLPOLYTopologyReader
   : public TopologyReader
{
public:
    DLPOLYTopologyReader() {}

    /// read a topology file
    bool ReadTopology(string file, Topology &top);

    /// set the topology file name: <name>.dlpf (convention: ".dlpf"="FIELD")
    void   setFname(string name) { _fname = name; return; }
    /// get the topology file name: <name>.dlpf (convention: ".dlpf"="FIELD")
    string getFname()            { return _fname; }

private:
    string _fname;
    /// function to find and read the next line starting with a keyword/directive (skipping comments starting with "#" or ";")
    string _NextKeyline(ifstream &fs, const char* wsp);
    /// function to read the next line containing only a given keyword and an integer value after it (only skipping comments!)
    string _NextKeyInt(ifstream &fs, const char* wsp, const string &word, int &ival);
    /// function to check if the given (last read) directive line starts with a given keyword and has an integer value at the end
    bool   _isKeyInt(const string &line, const char* wsp, const string &word, int &ival);
};
```

I do not really care what is decided, I was working on the pdbreader and figured I would offer to do this just for the purpose of having consistency across the readers. After all there is always the risk of introducing bugs when you change code. :) 

Here is a more hands on reason. When I created the pdbreader I split it into two files because I saw that was what other people had done. Then @junghans wanted them in a single file, to reduce redundant code. If there had not been two separate files for trajectory and topology files for some of the readers to begin with I would not have made that mistake. Granted, I could have just asked before I started working on it.

**Comment by abrukhno** [comment]
By the rule of thumb "if it works and no change is necessitated, do not touch it", I would leave it as it is. :)

**Comment by JoshuaSBrown** [comment]
Ok, well I guess that settles it. :)
