### ISSUE TITLE
Consolidate gmx readers into single file 

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#232]
For the sake of consistency in the design of file input readers. It makes some sense to confine the readers to a single file. Though this is not exactly a high priority.

**Comment by junghans** [comment]
There isn't much sense the gmx topology reader wraps around `read_tpx()`, while the gmx trajectory reader wraps around `read_first_frame()`and `read_next_frame()`. So besides combining these two call for the gmx trajectory reader (see #41), there isn't much in  code duplication to fix.

However, on the plus side one could use `.tpr` as a trajectory and `.trr` as a toplogy, but I am not sure how useful that is.

**Comment by JoshuaSBrown** [comment]
Hmm... yes, this is definitely not a high priority task, but I suppose the more options the user has the better. I think this is a bigger issue when you consider that some people might just want to do the charge transport simulations and don't really care to use csg for whatever reason. Then they might be stuck with some file that they have been given. 
I have my first question: the flags (GMX == 52) is this for the version number 5.1. I'm guessing there was some restructuring when they updated the versions? Is this a flag defined in one of the gromacs files, or is it passed in somewhere?

**Comment by JoshuaSBrown** [comment]
Also, do you by chance have any of the gmx file types lying around I could test on? I did not see the .trr or tpr file types in the csg tutorial but I could have missed them.

**Comment by junghans** [comment]
> Also, do you by chance have any of the gmx file types lying around I could test on? I did not see the .trr or tpr file types in the csg tutorial but I could have missed them.

There is a `run.sh` in most `atomistic` folder, but:
```
gmx grompp -v
```
will generate a `.tpr` file and
```
gmx mdrun -v
```
will generate a `.trr` (or `.xtc`) trajectory.

**Comment by junghans** [comment]
> I have my first question: the flags (GMX == 52) is this for the version number 5.1. I'm guessing there was some restructuring when they updated the versions? Is this a flag defined in one of the gromacs files, or is it passed in somewhere?

The `GMX` flags is the ABI version of libgromacs (formerlt `libgmx`) we are linking against. Gromacs-5.1 has `GMX=51` and Gromacs-2016 has `GMX=52`. Currently Gromacs master used `GMX=52` as well. At some point VOTCA supported `GMX=50` and `45` and `40`, but as upstream stopped supporting <=Gromacs-5.0, we removed support for these APIs, too.

`libgromacs` itself is backwards-compstible, so we can still read older versions of Gromacs files, we just require a newer Gromacs version to be used.

**Comment by junghans** [comment]
Let's leave this for a later time, e.g. the next time the gmx API changes.

**Comment by junghans** [comment]
In #238, I switched back from Votca's internal number (e.g. `GMX=52`) to Gromacs' native numbering (e.g. `GROMACS_VERSION=20160000`).

**Comment by JoshuaSBrown** [comment]
Does this mean that gmx consolidation of the readers is on the table?

**Comment by junghans** [comment]
No, but at least we follow upstream versioning scheme now!
