### ISSUE TITLE
Consolidate mdp readers into single file. 

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#233]
For the sake of consistency in the design of file input readers. It makes some sense to confine the readers to a single file. Though this is not exactly a high priority.

**Comment by junghans** [comment]
The mdp format is some internal format for the IMC code of  Alexander Lyubartsev. Nobody has used it recently and it is not even compiled-in anymore. Most of their users use the [MagiC package](http://www.fos.su.se/~sasha/magic/) these days.

**Comment by JoshuaSBrown** [comment]
Does this mean the mdp readers are essentially deprecated, un-supported?

**Comment by junghans** [comment]
Yes, I guess we should remove it!

@ruehle, any objections?

**Comment by junghans** [comment]
Ok, let's drop them!
