### ISSUE TITLE
Memory issue found in csg_stat when using valgrind

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#282]

**Comment by JensWehner** [comment]
details?

**Comment by JoshuaSBrown** [comment]
Here the error was found to come from tools:
https://github.com/votca/tools/pull/73

**Comment by JoshuaSBrown** [comment]
Two other errors were found in csg stat, they were found to be related to a failure to initialize the _time variable in the Topology class as well as inappropriate use of the tools::threads class. The Run method is only meant to be used internally and it was being called directly within csgapplication.

**Comment by JoshuaSBrown** [comment]
Issues are also being addressed here: https://github.com/votca/csg/pull/283
and here: https://github.com/votca/tools/pull/80

**Comment by junghans** [comment]
See #294
