### ISSUE TITLE
get_simulation_setting does not find 'ref-t' in mdp file

### ISSUE THREAD

**Issue by marvinbernhardt** [votca/csg#286]
At least since Version 5.1[1] Gromacs allows the use of underscore or minus in its mdp options.
Votca only supports 'ref_t' when reading the temperature from an mdp file[2].
Therefore I get errors such as:
```
ERROR: 
get_simulation_setting: could not fetch ref_t from grompp.mdp and no default given, please add it in there
For details see the logfile inverse.log
```
Since in the online documentation of Gromacs reports all options with a minus, it would be nice if Votca would allow both, minus and underscore.

1. http://manual.gromacs.org/documentation/5.1-current/user-guide/mdp-options.html
2. https://github.com/votca/csg/blob/master/share/scripts/inverse/functions_gromacs.sh

**Comment by junghans** [comment]
Can you try in the patch if #287 helps?

**Comment by marvinbernhardt** [comment]
Tested with ref-t and it works, thanks a lot :)
