### ISSUE TITLE
Refactor Beadtype

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#305]
The GetOrCreateBeadType method in the topology class is ambiguous. Given that there should only exist a set number of beadtypes careful consideration should be made when creating them. As it might be possible that two topology classes create their own bead types, if one of the topology classes is temporary any beads pointing to the beadtypes stored in that class will lead to undefined behavior. It is better therefore to break up the GetOrCreateBeadTypes into 3 separate methods:

CreateBeadType - should only be called when there truly does not exist a beadtype 
AddBeadType - if there already exists a bead type but it does not exist for the particular topology instance under consideration
BeadTypeExist - determine if the beady type already exist within the topology instance.

**Comment by JoshuaSBrown** [comment]
The pull request here: https://github.com/votca/csg/pull/303
should fix the seg faults but it does not account for correct treatement of the beadtype in all circumstances. For instance if the topology object is copied.

**Comment by JensWehner** [comment]
I think the problem i, it is not clear who owns what. I think the best solution would be to make clear, who owns which data and than write good copy constructors for it.

**Comment by JensWehner** [comment]
Maybe rename stuff that does not hold ownership to x_view e.g. molecule to molecule_view

**Comment by JensWehner** [comment]
Looking around in the code I see a lot more `new ` than `delete`

**Comment by JoshuaSBrown** [comment]
This is being handled in this branch:
https://github.com/votca/csg/tree/joshs-development
