### ISSUE TITLE
replace GNU gsl by lapack

### ISSUE THREAD

**Issue by GoogleCodeExporter** [votca/csg#32]
```
We are just using qr solve, which also available via lapack.
And lapack is also available on HPC machines.
```

Original issue reported on code.google.com by `christop...@gmail.com` on 7 Dec 2010 at 3:44
- Blocked on: #115

**Comment by junghans** [comment]
@symashayak : Are we using any gsl calls in `csg_re`?

**Comment by symashayak** [comment]
yes, it uses gsl for

votca::tools::linalg_cholesky_solve()

**Comment by JensWehner** [comment]
Yeah,

but we can use a direct LAPACK call there, in tools al the gsl calls would
have to be changed.

2016-09-27 18:39 GMT+02:00 Sikandar Y. Mashayak notifications@github.com:

> yes, it uses gsl for
> 
> votca::tools::linalg_cholesky_solve()
> 
> On Tue, Sep 27, 2016 at 8:46 AM, Christoph Junghans <

**Comment by junghans** [comment]
Switching to Eigen
