### ISSUE TITLE
LAMMPS data reader has a problem with comments and title lines

### ISSUE THREAD

**Issue by junghans** [votca/csg#370]
From https://groups.google.com/d/msg/votca/xzuifTrkEm4/e2STRdI7DAAJ with [lammpsTopology.xml](https://github.com/votca/csg/files/3089620/lammpsTopology.xml.txt), [cg_mapping.xml](https://github.com/votca/csg/files/3089622/cg_mapping.xml.txt), [pt_mapping.xml](https://github.com/votca/csg/files/3089624/pt_mapping.xml.txt), [settings.xml.txt](https://github.com/votca/csg/files/3089625/settings.xml.txt) and [propane_water_eq.data](https://github.com/votca/csg/files/3089647/propane_water_eq.data.txt)

```
$ csg_stat --top lammpsTopology.xml --cg "cg_mapping.xml;pt_mapping.xml" --options settings.xml --trj propane_water_eq.data
begin to calculate distribution functions
# of bonded interactions: 0
# of non-bonded interactions: 3
I have 1550 beads in 250 molecules
I have 250 beads in 250 molecules for the coarsegraining
an error occurred:
Unrecognized line in lammps .data file:
LAMMPS data file for propane_water_eq  environment is not set.
```
Removing the first two line give another error:
```
Unrecognized line in lammps .data file:
1   0.111100 3 0 0.0     # X C_3 C_3 X (H_ C_3 C_3 C_3)
```

**Comment by JoshuaSBrown** [comment]
Will take a look, just now seeing this.
