### ISSUE TITLE
Build from branch stable with GMX 2018 failes

### ISSUE THREAD

**Issue by jkrajniak** [votca/csg#391]
I've try to build votca-csg from `stable` branch but it failes with the following message:

```
[ 58%] Building CXX object csg/src/libcsg/CMakeFiles/votca_csg.dir/modules/io/growriter.cc.o
/user/leuven/307/vsc30783/vsc_data/software/2018a/votca/1.5/src/votca/csg/src/libcsg/modules/io/gmxtopologyreader.cc(53): error: class "gmx_mtop_t" has no member "nmolblock"
      size_t nmolblock=mtop.nmolblock;
                            ^

/user/leuven/307/vsc30783/vsc_data/software/2018a/votca/1.5/src/votca/csg/src/libcsg/modules/io/gmxtopologyreader.cc(76): error: class "gmx_molblock_t" has no member "natoms_mol"
              size_t natoms_mol = mtop.molblock[iblock].natoms_mol;
                                                        ^

```

GROMACS: 2018.7
Compiler: Intel 18.0.1.2017018
Boost: 1.68

**Comment by JoshuaSBrown** [comment]
You might have more success with clang, or gcc. What cmake flags did you use?

**Comment by junghans** [comment]
The build with gmx2018 passes in the CI:
https://gitlab.com/votca/votca/-/jobs/270053456

I thought https://github.com/votca/csg/commit/5963e51809d1b33131c0ee1f5042ad0734834f65#diff-6ec9b941bc3f09d6b331595a497e55e5 had fixed that issue.
