### ISSUE TITLE
FMatch gets different results in development

### ISSUE THREAD

**Issue by JensWehner** [votca/csg#399]

**Comment by junghans** [comment]
For https://github.com/votca/votca/pull/175

**Comment by junghans** [comment]
@JensWehner can you have a look at this?

**Comment by JensWehner** [comment]
@junghans I am on holiday for the next two weeks. Afterwards okay?

**Comment by junghans** [comment]
Sure, no worries.

**Comment by JensWehner** [comment]
So the fmatch discrepancies come from the different accuracy of the read in trajectories. 

The old trajectories had 9 digits for forces
The new ones have 6 
Due to the unit conversion I could not exactly reproduce that. But with 9 digits precision in the forces I got changes of the same magnitude as shown before. 

I cannot completely rule out, that fmatch was changed, but I think that the difference is due to the file parser and not some internal changes.

**Comment by junghans** [comment]
Can we update our test case to use 9 digits for the forces?

**Comment by JensWehner** [comment]
https://github.com/votca/csg/compare/152f360bd762...58e70a1218a8

**Comment by junghans** [comment]
Fixed
