### ISSUE TITLE
Regression LAMMPS test in dev fail

### ISSUE THREAD

**Issue by JensWehner** [votca/csg#401]
On ubuntu it cannot find the executable name "lammps" as it is looking for "lmp". So no test starts

**Comment by JoshuaSBrown** [comment]
Can you provide more of a description? Which pull request are you having trouble with?

**Comment by JoshuaSBrown** [comment]
@JensWehner I think the reason the tests were failing is because the pull request in csg-tutorials was never merged. 

https://github.com/votca/csg-tutorials/pull/49

well at least it passes on travis.

**Comment by junghans** [comment]
Good point I still want to check if why the realtime example gave such strange results.

**Comment by junghans** [comment]
for https://github.com/votca/votca/pull/175

**Comment by junghans** [comment]
I reactived the lammps test in https://github.com/votca/csg-tutorials/commit/80bc6581471a744b85a5ae108e9585386a01398b and fixed the units in https://github.com/votca/csg-tutorials/commit/d861b41da7044b63823605353580b9622b78f0cf, but the `re_lammps` still have unclear units to me.

**Comment by junghans** [comment]
`csg_reupdate` reads `kBT` in https://github.com/votca/csg/blob/master/src/tools/csg_reupdate.cc#L180, so energy scale should be right and length scale is already.

@symashayak do I miss anything here?

**Comment by junghans** [comment]
> On ubuntu it cannot find the executable name "lammps" as it is looking for "lmp". So no test starts

Did you fix that in 7f81b80d5?

**Comment by JensWehner** [comment]
okay it works

**Comment by junghans** [comment]
@JensWehner @JoshuaSBrown was the realtime example now working?

**Comment by JensWehner** [comment]
on my machine yes

**Comment by junghans** [comment]
Thanks!
