### ISSUE TITLE
refactor imc solve

### ISSUE THREAD

**Issue by junghans** [votca/csg#407]
Inside the scripts it calls:
```
linsolve.py --reg 0 CG-CG.packed CG-CG.packed.sol
```

which reads `CG-CG.packed.gmc` and `CG-CG.packed.imc` and writes results to `CG-CG.packed.sol`.

Example files from SPCE tutorials:
[CG-CG.packed.gmc](https://github.com/votca/csg/files/3623838/CG-CG.packed.gmc.txt)
[CG-CG.packed.imc](https://github.com/votca/csg/files/3623839/CG-CG.packed.imc.txt)
[CG-CG.packed.sol](https://github.com/votca/csg/files/3623840/CG-CG.packed.sol.txt)

**Comment by junghans** [comment]
More realistic input:
[CG-CG.packed.gmc](https://github.com/votca/csg/files/3631584/CG-CG.packed.gmc.txt)
[CG-CG.packed.imc](https://github.com/votca/csg/files/3631585/CG-CG.packed.imc.txt)
[CG-CG.packed.sol](https://github.com/votca/csg/files/3631587/CG-CG.packed.sol.txt)

**Comment by junghans** [comment]
Unpacked inputs:
[CG-CG.gmc](https://github.com/votca/csg/files/3636121/CG-CG.gmc.txt)
[CG-CG.idx](https://github.com/votca/csg/files/3636122/CG-CG.idx.txt)
[CG-CG.imc](https://github.com/votca/csg/files/3636124/CG-CG.imc.txt)

**Comment by junghans** [comment]
[CG-CG.dpot.imc](https://github.com/votca/csg/files/3636922/CG-CG.dpot.imc.txt)
[CG-CG.gmc](https://github.com/votca/csg/files/3636924/CG-CG.gmc.txt)
[CG-CG.idx](https://github.com/votca/csg/files/3636926/CG-CG.idx.txt)
[CG-CG.imc](https://github.com/votca/csg/files/3636927/CG-CG.imc.txt)
[CG-CG.packed.gmc](https://github.com/votca/csg/files/3636929/CG-CG.packed.gmc.txt)
[CG-CG.packed.idx](https://github.com/votca/csg/files/3636931/CG-CG.packed.idx.txt)
[CG-CG.packed.imc](https://github.com/votca/csg/files/3636932/CG-CG.packed.imc.txt)
[CG-CG.packed.sol](https://github.com/votca/csg/files/3636933/CG-CG.packed.sol.txt)

**Comment by JensWehner** [comment]
all the packed stuff is intermediate stuff? So we go from 

CG-CG.gmc
CG-CG.idx -> CG-CG.dpot.imc
CG-CG.imc

?

**Comment by junghans** [comment]
Yes

**Comment by JensWehner** [comment]
But the potential solve and then unpack can be executed more than once for different pairs? That is also the part with the regularisation parameter?

**Comment by junghans** [comment]
Yes, It is done for each IMC group. But solve and unpack are only done once for each group.

**Comment by junghans** [comment]
@DRosen285 any comments?

**Comment by junghans** [comment]
Done in #411
