### ISSUE TITLE
csg_dump cannot read pdb

### ISSUE THREAD

**Issue by junghans** [votca/csg#412]
From https://groups.google.com/d/msg/votca/ldn3dPtJ9Lg/f0XKIrWDBAAJ
```
$ csg_dump --top viton4_10_20_pcff_1.data.mapx.new_v5.pdb
an error occurred:
Misformated pdb file in atom line # 0
 the correct pdb file format requires 80 characters in width. Furthermore,
 to read the topology in from a .pdb file the following attributes must be
 specified:
 Atom Name, Residue Name, Residue Number, x, y, z, charge (optional)
```

With [viton4_10_20_pcff_1.data.mapx.new_v5.pdb](https://github.com/votca/csg/files/3636838/viton4_10_20_pcff_1.data.mapx.new_v5.pdb.txt)

**Comment by junghans** [comment]
Apparently we read the atomtype from the wrong column, see: https://groups.google.com/d/msg/votca/ldn3dPtJ9Lg/ahMJdqElBQAJ

**Comment by junghans** [comment]
@JensWehner can you have a look at this?

**Comment by JoshuaSBrown** [comment]
@junghans does this need to be fixed in development of stable?

**Comment by junghans** [comment]
I would fix it in stable if possible.
