### ISSUE TITLE
imc tests hang on csg_repack

### ISSUE THREAD

**Issue by junghans** [votca/csg#418]
If you run the IMC tutorials they hang in `csg_imcrepack` using https://github.com/votca/votca/pull/191:
```
cmake .. -DENABLE_TESTING=ON -DENABLE_REGRESSION_TESTING=ON -DENABLE_EXPERIMENTAL_TESTS=ON
make
ctest -V -R LJ
...
solving linear equations for imc group 'group_1' (regularization 1000)
```

`csg_imcrepack` was only touched in 16e43ee22a497122854ed7de2a6171528163b23b, if I revert that commit it fails on the unpack after running `csg_imc_solve` with:
```
Running critical command 'csg_imcrepack --in group_1.packed --unpack group_1.packed.sol'
terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid range 61:60: begin, end and stride do not form a closed interval
```

**Comment by junghans** [comment]
And this problems persists even before #411 (e.g. with ecad9be9c00bedc67b5145d15b515306365de641 and votca/csg-tutorials@9e75a8e237aa8a15a688545cdfd0c4b8f90d91f3)

However the spce/imc (`ctest -V -R spce_imc`) passes.

**Comment by junghans** [comment]
Semi-good news, using  votca/votca#191 and reverting 16e43ee (`git revert 16e43ee`), I get the spce/imc to pass. So there are two bugs, one in 16e43ee and another one in the LJ example I still have to track down.

**Comment by DRosen285** [comment]
The .packed.imc files look weird for the LJ example. It seems that single lines are getting written multiple times. In my case the same line gets written 60 times,.

**Comment by junghans** [comment]
Another semi-good news, with `v1.5` the `LJ` example still works, the call sequence is something like:
```
Running critical command 'csg_imcrepack --in group_1 --out group_1.packed'
written group_1.packed.imc
written group_1.packed.gmc
written group_1.packed.idx
Running subscript 'solve_numpy.sh group_1.packed group_1.packed.sol 1000 1000 1000' (from tags imcsolver numpy) dir /home/christoph/votca/src/votca/csg/share/scripts/inverse
Running subscript 'linsolve.py --reg 1000 group_1.packed group_1.packed.sol' (from tags solve numpy) dir /home/christoph/votca/src/votca/csg/share/scripts/inverse
Running critical command 'sed -ie s/NaN/0.0/ group_1.packed.sol'
Running critical command 'sed -ie s/Inf/0.0/ group_1.packed.sol'
Running critical command 'csg_imcrepack --in group_1.packed --unpack group_1.packed.sol'
```
The input and outfiles for a very short run with 5000 md steps are:
[group_1.gmc](https://github.com/votca/csg/files/3655994/group_1.gmc.txt)
[group_1.idx](https://github.com/votca/csg/files/3655997/group_1.idx.txt)
[group_1.imc](https://github.com/votca/csg/files/3655999/group_1.imc.txt)
[group_1.packed.gmc](https://github.com/votca/csg/files/3656005/group_1.packed.gmc.txt)
[group_1.packed.idx](https://github.com/votca/csg/files/3656006/group_1.packed.idx.txt)
[group_1.packed.imc](https://github.com/votca/csg/files/3656008/group_1.packed.imc.txt)
[group_1.packed.sol](https://github.com/votca/csg/files/3656010/group_1.packed.sol.txt)
[LJ1-LJ1.dpot.imc](https://github.com/votca/csg/files/3656011/LJ1-LJ1.dpot.imc.txt)
[LJ1-LJ2.dpot.imc](https://github.com/votca/csg/files/3656013/LJ1-LJ2.dpot.imc.txt)
[LJ2-LJ2.dpot.imc](https://github.com/votca/csg/files/3656014/LJ2-LJ2.dpot.imc.txt)

**Comment by JensWehner** [comment]
Can you tell me where and what I can do?

**Comment by junghans** [comment]
```
cmake .. -DENABLE_TESTING=ON -DENABLE_REGRESSION_TESTING=ON -DENABLE_EXPERIMENTAL_TESTS=ON
make
ctest -V -R spce_imc
```

Are the files are inside the build directory and then `csg-tutorials/spce/imc/step_001`.

**Comment by junghans** [comment]
@JensWehner with
```patch
diff --git a/src/libcsg/imcio.cc b/src/libcsg/imcio.cc
index 83011841..0509c0a7 100644
--- a/src/libcsg/imcio.cc
+++ b/src/libcsg/imcio.cc
@@ -65,7 +65,7 @@ void imcio_write_matrix(const string &file, const Eigen::MatrixXd &gmc,
   if (list == nullptr) {
     for (int i = 0; i < gmc.rows(); ++i) {
       for (int j = 0; j < gmc.cols(); ++j) {
-        out_A << gmc(i, j) << " ";
+        out_A << gmc(min(i, j), max(i, j)) << " ";
       }
       out_A << endl;
     }
```
`csg_imcrepack` will work, but then `csg_imc_solve` will hang.
