### ISSUE TITLE
IMC: remove potential crop

### ISSUE THREAD

**Issue by junghans** [votca/csg#429]
Related to https://github.com/votca/csg-tutorials/issues/59.

It seems to me that with only support non-zero rdf regions, we should be able to remove the potential crop in the IMC update.

/cc @DRosen285

**Comment by abrukhno** [comment]
I am not sure I quite follow this potential cropping issue. For me the major issue when using IMC was interruptions in the IMC iteration when a few empty bins were found in RDFs between non-zero data - most often in the decaying tails, where one could perhaps merely skip those points with the rest of the tail altogether. - Is it what you call 'potential cropping'?

That is apart from extremely long computation times for cross-correlations with more than 2 potentials at once.

**Comment by junghans** [comment]
@abrukhno cropping just removes the first (max. 3) point in a delta potential if the slope isn't monotonic. 

Your issues of non-contiguous ranges and slow performance for cross-correlation calculation are independent, but there isn't an easy solution to these issue.
