### ISSUE TITLE
VOTCA-CSG Wiki is really out of date

### ISSUE THREAD

**Issue by JensWehner** [votca/csg#472]
the wiki of this repo has lots of outdated information. 

e.g.
https://github.com/votca/csg/wiki/BugFix

Should we delete it, because 95% of the relevant information is in votca/votca

**Comment by junghans** [comment]
Ok, just remove it and replace it with a link to the new documentation!

**Comment by JensWehner** [comment]
I did most of it.

**Comment by JensWehner** [comment]
Last time we talked about it, you wanted to keep the rest of it? I mean I do not mind deleting the rest. But I do not know how up to date it is.

**Comment by junghans** [comment]
Just delete everything, but https://github.com/votca/csg/wiki/Installing, the wiki is in git after all, so we can always revert.

**Comment by JensWehner** [comment]
done.
