### ISSUE TITLE
CMake VERSION needs to be bumped in master

### ISSUE THREAD

**Issue by JoshuaSBrown** [votca/csg#568]
Currently, master is using some variables that only appear to be available after 3.14 e.g. CMAKE_INSTALL_BINDIR

**Comment by junghans** [comment]
There variables get defined by `GNUInstallDirs.cmake` for earlier versions of CMake, see:
https://github.com/Kitware/CMake/blob/v3.10.0/Modules/GNUInstallDirs.cmake#L36
