### ISSUE TITLE
IMC multicomponent working?

### ISSUE THREAD

**Issue by marvinbernhardt** [votca/csg#577]
Is there a working implementation of multicomponent IMC?

I'm trying with csg-tutorials/propane/imc, but only A-A gets updated. I took a look in src/tools/csg_stat_imc.cc, but with my low C++ skills I can't tell if multicomponent sampling of the IMC matrix is implemented or not. The resulting matrix all.gmc is zero everywhere except for the A-A block.

**Comment by junghans** [comment]
It should work, it might have something to do with `do_potential` in the `propane/imc` case, `A-A` get update in step 1, then `B-B` in step 2, then `A-B` in step 3 and so on. 

@DRosen285 knows more.

**Comment by marvinbernhardt** [comment]
I tried setting all `do_potential` to `1`, but it does not help.

**Comment by marvinbernhardt** [comment]
simple plot of all.gmc
![imc-mat](https://user-images.githubusercontent.com/25516935/90337455-cd687780-dfe2-11ea-94a6-2e16e91a8486.png)

**Comment by junghans** [comment]
Are all interactions in the `all` group?

**Comment by marvinbernhardt** [comment]
yes

**Comment by junghans** [comment]
Does the `LJ1-LJ2/imc` example works as expected?

**Comment by marvinbernhardt** [comment]
Nope. I try with do_potential = 1, short number of frames and votca master branch.
![imc-mat](https://user-images.githubusercontent.com/25516935/90338211-34d4f600-dfe8-11ea-9934-aed512ad879f.png)

**Comment by junghans** [comment]
@DRosen285 do you have any idea?

**Comment by marvinbernhardt** [comment]
https://github.com/votca/csg/blob/00db20e927a7a76554692a8c4f4d684c933433e7/src/tools/csg_stat_imc.cc#L691
This line seems to be the problem. I don't know why yet, but it seems to insert all matrices at the top right corner of gmc. Found out by writing gmc and M.transpose().eval() at the end of each pair.

**Comment by marvinbernhardt** [comment]
> https://github.com/votca/csg/blob/00db20e927a7a76554692a8c4f4d684c933433e7/src/tools/csg_stat_imc.cc#L691
> 
> This line seems to be the problem. I don't know why yet, but it seems to insert all matrices at the top right corner of gmc. Found out by writing gmc and M.transpose().eval() at the end of each pair.

`i` and `j` are not correct I think. When printed they are 0-2. But they should be offsets, right?
https://github.com/votca/csg/blob/00db20e927a7a76554692a8c4f4d684c933433e7/src/tools/csg_stat_imc.cc#L683-L684

**Comment by DRosen285** [comment]
So I just checked, v1.5 (the last version I used) via docker. There the LJ1-LJ2/imc example works.

There is a slight difference in that part in v1.5:

    661             int i=pair->_offset_i;
    662             int j=pair->_offset_j;

So maybe by re-writing that part sth.went wrong.

**Comment by marvinbernhardt** [comment]
This seems to be broken since https://github.com/votca/csg/commit/edeab35411d18882b08872c0c83435f87d9d7825#
Before the offsets in `pair_t` where correctly generated.

https://github.com/votca/csg/blob/00db20e927a7a76554692a8c4f4d684c933433e7/src/tools/csg_stat_imc.cc#L493-L503

**Comment by JensWehner** [comment]
Okay that was me then.

**Comment by marvinbernhardt** [comment]
> Okay that was me then.

Wanna fix it or should I try?

**Comment by JensWehner** [comment]
Go ahead. I have no idea. If you need any help let me know. :)

**Comment by junghans** [comment]
I blame @JensWehner

**Comment by JensWehner** [comment]
I think it is the `InitializeGroups()` refactoring. The new indices `i` and `j` seem wrongly computed.

**Comment by JensWehner** [comment]
@junghans all the tests worked.. so we have to fix that part.

**Comment by junghans** [comment]
Yeah we don’t have a multi-component test.
