### ISSUE TITLE
Error during IBI csg Tutorial of liquid Hexane

### ISSUE THREAD

**Issue by mangesh-bhendale** [votca/csg#590]
I am trying to perform Hexane tutorial. I finished the atomistic simulation of hexane and got the A-A, A-B, B-B rd's and bond and angle distribution also. Now, while I am trying to to the IBI coarse graining an occurred and this was mentioned in the onverse.log file:

For a more verbose log see: inverse.log
csg_get_property: No value for 'cg.inverse.mpi.tasks' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.mpi.tasks'
csg_get_property: No value for 'cg.inverse.mpi.cmd' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.mpi.cmd'
csg_get_property: No value for 'cg.inverse.parallel.tasks' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.parallel.tasks'
csg_get_property: No value for 'cg.inverse.parallel.cmd' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.parallel.cmd'
csg_get_property: No value for 'cg.inverse.gromacs.mdrun.bin' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.gromacs.mdrun.bin'
csg_get_property: No value for 'cg.inverse.espresso.bin' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.espresso.bin'
csg_get_property: No value for 'cg.inverse.scriptdir' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.scriptdir'
csg_get_property: No value for 'cg.inverse.gromacs.grompp.topol' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.gromacs.grompp.topol'
csg_get_property: No value for 'cg.inverse.gromacs.grompp.index' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.gromacs.grompp.index'
csg_get_property: No value for 'cg.inverse.gromacs.g_rdf.topol' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.gromacs.g_rdf.topol'
csg_get_property: No value for 'cg.inverse.convergence_check' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.convergence_check'
csg_get_property: No value for 'cg.inverse.convergence_check_options.name_glob' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.convergence_check_options.name_glob'
csg_get_property: No value for 'cg.inverse.convergence_check_options.limit' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.convergence_check_options.limit'
csg_get_property: No value for 'cg.inverse.espresso.table_end' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.espresso.table_end'
csg_get_property: No value for 'cg.inverse.gromacs.traj_type' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml
csg_get_property: returning emtpy value for 'cg.inverse.gromacs.traj_type'
csg_get_property: No value for 'cg.inverse.gromacs.topol_out' found in /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying /share/votca/xml/csg_defaults.xml

I checked the settings.xml file; but above mentioned things are not present there. I am unable to understand the error.

Please help.

**Comment by junghans** [comment]
On Tue, Sep 1, 2020, 03:52 mangesh-bhendale <notifications@github.com>
wrote:

> I am trying to perform Hexane tutorial. I finished the atomistic
> simulation of hexane and got the A-A, A-B, B-B rd's and bond and angle
> distribution also. Now, while I am trying to to the IBI coarse graining an
> occurred and this was mentioned in the onverse.log file:
>
> For a more verbose log see: inverse.log
> csg_get_property: No value for 'cg.inverse.mpi.tasks' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.mpi.tasks'
> csg_get_property: No value for 'cg.inverse.mpi.cmd' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.mpi.cmd'
> csg_get_property: No value for 'cg.inverse.parallel.tasks' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.parallel.tasks'
> csg_get_property: No value for 'cg.inverse.parallel.cmd' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.parallel.cmd'
> csg_get_property: No value for 'cg.inverse.gromacs.mdrun.bin' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.gromacs.mdrun.bin'
> csg_get_property: No value for 'cg.inverse.espresso.bin' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.espresso.bin'
> csg_get_property: No value for 'cg.inverse.scriptdir' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.scriptdir'
> csg_get_property: No value for 'cg.inverse.gromacs.grompp.topol' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for
> 'cg.inverse.gromacs.grompp.topol'
> csg_get_property: No value for 'cg.inverse.gromacs.grompp.index' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for
> 'cg.inverse.gromacs.grompp.index'
> csg_get_property: No value for 'cg.inverse.gromacs.g_rdf.topol' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for
> 'cg.inverse.gromacs.g_rdf.topol'
> csg_get_property: No value for 'cg.inverse.convergence_check' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.convergence_check'
> csg_get_property: No value for
> 'cg.inverse.convergence_check_options.name_glob' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for
> 'cg.inverse.convergence_check_options.name_glob'
> csg_get_property: No value for
> 'cg.inverse.convergence_check_options.limit' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for
> 'cg.inverse.convergence_check_options.limit'
> csg_get_property: No value for 'cg.inverse.espresso.table_end' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.espresso.table_end'
> csg_get_property: No value for 'cg.inverse.gromacs.traj_type' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
> csg_get_property: returning emtpy value for 'cg.inverse.gromacs.traj_type'
> csg_get_property: No value for 'cg.inverse.gromacs.topol_out' found in
> /root/votca/csg-tutorials/hexane/ibi_all/settings.xml, trying
> /share/votca/xml/csg_defaults.xml
>
> I checked the settings.xml file; but above mentioned things are not
> present there. I am unable to understand the error.
>
There aren't errors, it just means there is no default value for these
properties.

What are the last couple of lines before the error message? Or attach the
whole inverse.log here.

Christoph

**Comment by mangesh-bhendale** [comment]
Yes, I did not find any default values of those parameters. Where can I find them?

I am attaching the inverse.log file here.
[inverse.log](https://github.com/votca/csg/files/5156470/inverse.log)

**Comment by junghans** [comment]
On Tue, Sep 1, 2020 at 07:29 mangesh-bhendale <notifications@github.com> wrote:
>
>
>
> Yes, I did not find any default values of those parameters. Where can I find them?
>
>
>
> I am attaching the inverse.log file here.
>
>
> inverse.log

If you look at the very end it says “gmx_d grompp” failed and if you
scroll a bit up

Fatal error:
The group cutoff scheme has been removed since GROMACS 2020. Please use the
Verlet cutoff scheme.

In short, to do coarse-graining you basically need to use gmx-2019.*
(or lammps) as the current gromacs version has no support for
tabulated interactions.
(see and comment on https://gitlab.com/gromacs/gromacs/-/issues/1347)

Cheers,

Christoph

**Comment by junghans** [comment]
A warning was added a while back to CMake in #452.
