### ISSUE TITLE
Fork bomb by csg_inverse if shared library missing

### ISSUE THREAD

**Issue by marvinbernhardt** [votca/csg#600]
When i do csg_inverse and i don't load the intel module (for mkl), it just says `Terminated`, no inverse.log is created, and lots of inverse.sh processes get spawned. Tested with the current master branch.
I don't really know where or how to debug this, so any ideas are welcome.

**Comment by junghans** [comment]
Can you try to run `csg_property --help`? And look for errors.

**Comment by JensWehner** [comment]
Was it compiled with MKL ?

**Comment by marvinbernhardt** [comment]
@junghans 
```
$ csg_property --help
csg_property: error while loading shared libraries: libmkl_core.so: cannot open shared object file: No such file or directory
```
@JensWehner 
Yes, it was. It was compiled with 
```module purge
module load gcc/7.3.1
module load boost/nompi/gcc/1.67.0
module load gsl/gcc/2.5
module load eigen/gcc/3.3.5
module load fftw/gcc/single/sse/3.3.8
module load fftw/gcc/double/sse/3.3.8
module load gromacs/nompi/cpu/gcc/single/2018.2
module load intel/env/2018
```
nd the problem occurs if I run it with all loaded but intel.

**Comment by JensWehner** [comment]
so your csg was compiled with intel. So csg needs to know where the MKL library is at runtime. If you do not load it csg will run and then try to call the mkl and then the error is thrown.

**Comment by junghans** [comment]
Could you build it with `-DENABLE_RPATH_INJECT=On`?

**Comment by marvinbernhardt** [comment]
> so your csg was compiled with intel. So csg needs to know where the MKL library is at runtime. If you do not load it csg will run and then try to call the mkl and then the error is thrown.

Ah yeah, it might actually compile with the intel compiler, did not realise this.
Anyway, I think it is correct to throw an error and stop. But the error message doesn't help, plus the infinite process spawning which is annoying.

**Comment by JensWehner** [comment]
It is not compiled with the intel compiler, it is probably linked against the intel math library, which votca does by default if it finds one on the system.

**Comment by JensWehner** [comment]
against the process spawning, I think that is part of the scripts @junghans

**Comment by marvinbernhardt** [comment]
> Could you build it with `-DENABLE_RPATH_INJECT=On`?

This fixes the problem!

**Comment by JensWehner** [comment]
@junghans can you explain why it fixes the problem? :)

**Comment by JensWehner** [comment]
ahh it basically tells votca, where these other libraries might be, so you do not have to load them. Clever...

**Comment by junghans** [comment]
It happens surprising often that libraroes can not be found a run time, so I think I will add a check to start sequence of csg_inverse to make the user aware of this issue instead of going into an endless fork bomb.

**Comment by junghans** [comment]
> ahh it basically tells votca, where these other libraries might be, so you do not have to load them. Clever...

Yeah basically this option makes votca remember where libraries were found at compile time and inject that path into the rpath of the installed binaries. But that doesn't work on all system though.

The main reason the fork bomb happens is that csg_inverse tries to read a value from the xml file and that fails due to missing library and then it tries to issue an error message for which it tries to read another value from the xml file and so on.
