### ISSUE TITLE
add a cmake option for in-source development

### ISSUE THREAD

**Issue by GoogleCodeExporter** [votca/csg#61]
```
-replace autotools by cmake
-replace netbeans by eclipse

```

Original issue reported on code.google.com by `christop...@gmail.com` on 16 Jan 2011 at 6:47

**Comment by junghans** [comment]
Super project has been start: votca/buildutil@f42ec0a66c04ee4a97cec7dc3546903d18bbb48d, see the [global](https://github.com/votca/buildutil/tree/global) branch for further development!

**Comment by junghans** [comment]
Done in new build system at https://github.com/votca/votca
