### ISSUE TITLE
build with gromacs master fails

### ISSUE THREAD

**Issue by junghans** [votca/csg#612]
```
[ 23%] Building CXX object tools/src/tests/CMakeFiles/unit_test_calculator.dir/test_calculator.cc.o
cd /__w/votca/votca/builddir/tools/src/tests && /usr/lib64/ccache/g++ -DBOOST_TEST_DYN_LINK -DTOOLS_TEST_DATA_FOLDER=\"/__w/votca/votca/tools/src/tests/DataFiles\" -I/__w/votca/votca/tools/include -I/__w/votca/votca/builddir/tools/include -I/__w/votca/votca/builddir/tools/include/votca/tools -isystem /usr/include/eigen3 -Wall -Wextra -Wpedantic -Wshadow -Wconversion -Werror -O2 -DNDEBUG -std=c++14 -o CMakeFiles/unit_test_calculator.dir/test_calculator.cc.o -c /__w/votca/votca/tools/src/tests/test_calculator.cc
Dependee "/__w/votca/votca/builddir/tools/src/tests/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/__w/votca/votca/builddir/tools/src/tests/CMakeFiles/unit_test_graph_bf_visitor.dir/depend.internal".
In file included from /__w/votca/votca/csg/src/libcsg/trajectoryreader.cc:32:
/__w/votca/votca/csg/src/libcsg/modules/io/gmxtrajectoryreader.h:30:10: fatal error: gromacs/fileio/trxio.h: No such file or directory
   30 | #include <gromacs/fileio/trxio.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [csg/src/libcsg/CMakeFiles/votca_csg.dir/build.make:449: csg/src/libcsg/CMakeFiles/votca_csg.dir/trajectoryreader.cc.o] Error 1
```

see e.g. in this build https://github.com/votca/votca/pull/505/checks?check_run_id=1360492224

**Comment by junghans** [comment]
@eirrgang what is the replacement for `trxio.h` in the current master?

**Comment by junghans** [comment]
Ok, I tracked it back to our `read_first_frame(oenv, &_gmx_status, (char *)_filename.c_str(), &_gmx_frame, TRX_READ_X | TRX_READ_V | TRX_READ_F))` and `read_first_frame()` is also missing in the new headers.

So @eirrgang how would I implement that these days?

**Comment by eirrgang** [comment]
I made a note to make sure those get restored with https://gitlab.com/gromacs/gromacs/-/merge_requests/795

I'm hoping to rally the troops and get https://gitlab.com/gromacs/gromacs/-/issues/3288 resolved in the next week or two. (Let me know if you can help.)

**Comment by junghans** [comment]
Thanks, let me know if there is a non-legacy way to do the same.

**Comment by eirrgang** [comment]
> Thanks, let me know if there is a non-legacy way to do the same.

There is not. Public access to the `gromacs/...` headers has been deprecated for some time. Obviously, they will not be permanently removed until use cases like VOTCA's have been addressed in `gmxapi/...` headers. It is unclear when (or if) that will happen.

As long as the `Gromacs::libgromacs` target is importable, it should continue to work as it has. At least, once #3288 is resolved. There will be a few bumps as we try to further isolate these headers to make future clean-up easier.

The `Gromacs::libgromacs` target should be removed for Gromacs 2022, but if we still haven't made progress with the C++ API, a `Gromacs::legacy_api` target will likely provide the same headers supported instead by `libgmxapi`.

**Comment by eirrgang** [comment]
Please try https://gitlab.com/gromacs/gromacs/-/commits/3288-fileio 

Feel free to contribute commits to that branch if needed.

Please follow up at https://gitlab.com/gromacs/gromacs/-/issues/3288

Thanks!

**Comment by junghans** [comment]
I can confirm `3288-fileio` works.
