### ISSUE TITLE
lammpsreader fails on files with windows line endings

### ISSUE THREAD

**Issue by junghans** [votca/csg#613]
Reported here: https://groups.google.com/g/votca/c/OSrrvJaYOqk/m/7UuSBJ0rAwAJ

Steps for reproduce:

- Get https://github.com/votca/csg-tutorials/blob/master/spce/ibi_lammps/spce.data
- Convert it to a Windows file, e.g. `unix2dos spce.data`
- Run the reader on it, e.g. `csg_dump --top spce.data`
- It will fail with error: `Unrecognized line in lammps .data file`, while the original files works

**Comment by JensWehner** [comment]
The question is, do we want to support that? Otherwise we do not support windows functionality either?

**Comment by junghans** [comment]
Well some editors save file with windows file ending, so we should. For the xml files we do it here: https://github.com/votca/tools/blob/079d9c28aa3be82f0ae9a7807b738a84cc9e5c67/include/votca/tools/getline.h#L37

**Comment by junghans** [comment]
The lammps reader is using said `getline()` function (https://github.com/votca/csg/blob/d7c94c5c8485b0f2bef4905efc2e3880fa8390fa/src/libcsg/modules/io/lammpsdatareader.cc#L120) so this is a bit strange.

@JensWehner any ideas?

**Comment by JensWehner** [comment]
my first thought is we should explicitly call `tools::getline` because maybe some parts call the wrong function?

**Comment by junghans** [comment]
> my first thought is we should explicitly call `tools::getline` because maybe some parts call the wrong function?

Good point that fixes it!
