### ISSUE TITLE
Parse xml descriptions into rst 

### ISSUE THREAD

**Issue by junghans** [votca/csg#618]
Following up from https://github.com/votca/csg-manual/pull/60, I was try to use `/extract_metadata.py` from xtp, but got the following error:
```
$ /home/junghans/votca/xtp/share/doc/extract_metadata.py -i topol.xml -m csg
Traceback (most recent call last):
  File "/home/junghans/votca/xtp/share/doc/extract_metadata.py", line 255, in <module>
    main()
  File "/home/junghans/votca/xtp/share/doc/extract_metadata.py", line 89, in main
    table = csg_create_rst_table(file_name)
  File "/home/junghans/votca/xtp/share/doc/extract_metadata.py", line 181, in csg_create_rst_table
    s += csg_get_recursive_attributes(elem)
  File "/home/junghans/votca/xtp/share/doc/extract_metadata.py", line 151, in csg_get_recursive_attributes
    description = wrap_line(description)
TypeError: wrap_line() missing 1 required positional argument: 'sep'
```

@felipeZ any idea?

**Comment by junghans** [comment]
Got it (see https://github.com/votca/xtp/pull/603)

**Comment by junghans** [comment]
@felipeZ can you look at the last table here: https://votca.github.io/csg-manual/index.html the formatting is a bit wrong.

**Comment by junghans** [comment]
Table formatting broken here: https://votca.github.io/csg-manual/reference.html#settings-file

**Comment by junghans** [comment]
We still need reference of the scripts and what options they use (section 10.5 of http://doc.votca.org/manual.pdf) AND program reference (section 10.1 of  http://doc.votca.org/manual.pdf)

**Comment by felipeZ** [comment]
@junghans when I built the csg-manually locally I get the following table:
 
![sample_settings](https://user-images.githubusercontent.com/4108663/101653175-59455a00-3a3f-11eb-997d-796445d3e9ea.jpg)

I think it is something in the css configuration

**Comment by felipeZ** [comment]
See [votca/votca/css](https://github.com/votca/votca/tree/css)

**Comment by junghans** [comment]
Let's merge votca/votca#535 and see what happens.

**Comment by felipeZ** [comment]
The table format seems to be fixed, also notice that there is a slider at the table's bottom, see below:
![slidebar](https://user-images.githubusercontent.com/4108663/101759693-32883180-3ada-11eb-87b4-0638acd70f08.jpg)

**Comment by junghans** [comment]
@felipeZ now all descriptions are gone....

**Comment by felipeZ** [comment]
@junghans  the problem is in the Python script and not in the `css` folder. The Python script is not extracting the descriptions correctly, I am going to fix that

**Comment by felipeZ** [comment]
@junghans  the descriptions should be back with [votca/votca#539](https://github.com/votca/votca/pull/539)

**Comment by junghans** [comment]
@felipeZ as discussed, can you swap the default and description column in https://www.votca.org/csg/reference.html

**Comment by junghans** [comment]
ping @felipeZ - to switch order to columns (see above)

**Comment by junghans** [comment]
@felipeZ ping
