### ISSUE TITLE
csg-stat does not read bead masses if they are certain numbers

### ISSUE THREAD

**Issue by rdguha95** [votca/csg#704]
There is some bug in the csg-stat reader when it comes to LAMMPS CG data files. The reader only reads bead masses if they are certain numbers. It happens when you are performing any type of ibi using lammps and can be shown even in the ibi_lammps example in the csg-tutorials folder in votca. 

The simulation is for CG water molecules with each bead having a mass of 18.01540. For this mass, the inversion will work and csg-stat will read the files from traj.dump like:-

These styles use the following formats in the atom block:
atom-ID molecule-ID atom-type charge x y z
atom-ID molecule-ID atom-type charge x y z nx ny nz
atom-ID molecule-ID atom-type x y z
atom-ID molecule-ID atom-type x y z nx ny nz
atom-ID atom-type x y z
atom-ID atom-type x y z nx ny nz

Unable to associate mass 18.01540 with element assuming pseudo atom, assigning name Bead1 .
Reading frame, timestep 10000
Reading frame, timestep 10100
Reading frame, timestep 10200
Reading frame, timestep 10300
Reading frame, timestep 10400
Reading frame, timestep 10500...

But if we change this mass to a hypothetical mass of 88.01540, the reader will stop recognizing the masses line and not read the mass.

WARNING: The votca lammps data reader is only able to read lammps files formatted in the following styles:
angle
atom
bond
full
molecule

These styles use the following formats in the atom block:
atom-ID molecule-ID atom-type charge x y z
atom-ID molecule-ID atom-type charge x y z nx ny nz
atom-ID molecule-ID atom-type x y z
atom-ID molecule-ID atom-type x y z nx ny nz
atom-ID atom-type x y z
atom-ID atom-type x y z nx ny nz

Reading frame, timestep 10000
an error occurred:
Topology does not have beads of type "Bead1"
This was specified in type1 of interaction "CG-CG"

**Comment by JensWehner** [comment]
Let me guess that you have an a bead with the name `Yttrium`.

The element names are inferred from the mass of the bead, which is quite fragile if your bead has a mass close to that of an element. Unfortunately there is no way to get from a lammps datafile if it is coarse grained or not.

But I think we should make the tolerance strighter. I propose this https://github.com/votca/tools/pull/378

**Comment by rdguha95** [comment]
So if a bead mass is close to an element name then it does not get read? Or it does get read but automatically assigned to an element? In that case if I rename my bead from bead 1 to Yttrium, should that work?

**Comment by rdguha95** [comment]
Another suggestion from our side would be :- Is it possible to do a conditional checking if the run is from LAMMPS and not perform element check if "TRUE".

**Comment by junghans** [comment]
I think we should go back to the old behavior where we did not try to detect the atom type and hence had no masses unless they were explicitly specified.

**Comment by rdguha95** [comment]
That would work too! But for now can anyone tell us what does VOTCA assign the bead to if it matches an element number. For my alanine simulation which has a bead of 88.1, it should correspond to Yttrium as Jens pointed out. I tried renaming Bead1 to both "Yttrium" and "Y", but I got the same error. 

What name is VOTCA assigning to this 88.1 mass bead if not Bead1/Yttrium/Y?

**Comment by rdguha95** [comment]
Never mind. I found it out using csg_dump --top topol.xml. It is assigning the 88.2 bead as Sr1

**Comment by junghans** [comment]
That is a good workaround using xml as topology file should work well.

**Comment by rdguha95** [comment]
We don't even have to use xml as a topology file. Just using csg_dump --top spce.data on the lammps data file also works. You just have to find the appropriate bead name and then rename the settings file accordingly

**Comment by JensWehner** [comment]
Yeah I am not pleased with the current solution. But I am not sure how to fix this. On the one hand people will complain if the all the beads have no element names. on the other hand this sucks for coarse-graining

**Comment by JensWehner** [comment]
@junghans is it possible to have coarse grained and atomic "beads" in the same simulation or is it all coarse grained vs all atomic?

**Comment by JensWehner** [comment]
We could also search for the existence of `H` atoms and see that as an indication that it is atomic. 

@junghans @rdguha95 can you give me rules, of which atomic masses most likely are atomic systems and which ones are coarse grained?

**Comment by junghans** [comment]
> @junghans is it possible to have coarse grained and atomic "beads" in the same simulation or is it all coarse grained vs all atomic?

Mixing of atomistic and coarse-grained is very unlikely

**Comment by junghans** [comment]
Fixed in #705
