### ISSUE TITLE
cmake: rewrite help2t2t into a cmake script or direct bump of manpage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [votca/csg#94]
```
help2t2t forces us to have bash as a dependency, most of the stuff could be 
done in cmake using string(regex replace ...) and so on.

```

Original issue reported on code.google.com by `christop...@gmail.com` on 16 May 2011 at 9:38

**Comment by junghans** [comment]
html target is not needed anymore and @capoe implemented tex out put for all app, so it should be easy to get rite of txt2tags once #187 is done.

**Comment by junghans** [comment]
This is done.
